name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Check Java and Maven version
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          mvn -v

      - name: Build with Maven
        run: mvn clean package

      - name: Run Main.java to generate dist/
        run: mvn exec:java
        
      - name: Deploy dist/ to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./dist

