name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Ensure required permissions are set for dependency submission
permissions:
  contents: read
  packages: read
  dependency-graph: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Check Java and Maven version
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          mvn -v

      - name: Build with Maven
        run: mvn clean package

      - name: Submit Maven dependencies
        uses: advanced-security/maven-dependency-submission-action@v4

      - name: Run Main.java to generate dist/
        run: java -cp target/classes com.ssg.Main

      - name: Deploy dist/ to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
